version: "3.7"
services:
  # Content meta-search engine
  searx1:
    build:
      context: ../libs/searx
    image: emerald/searx
    container_name: searx1

  searx2:
    build:
      context: ../libs/searx
    image: emerald/searx
    container_name: searx2

  searx3:
    build:
      context: ../libs/searx
    image: emerald/searx
    container_name: searx3

  searx4:
    build:
      context: ../libs/searx
    image: emerald/searx
    container_name: searx4

  searx_lb:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: emerald/searx-lb
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf
    container_name: searx_lb
    tty: true
    depends_on:
      - searx1
      - searx2
      - searx3
      - searx4
    ports:
      - "80:8080"